### PR TITLE
feat: respect single empty line

### PR DESCRIPTION
**Pull request by bram209**

### CODE REVIEW

**Comment by bram209** [comment]
resolves #27

**Comment by seblj** [comment]
Btw: This makes it so it does not respect no newlines when the closing tag is on a line by itself @bram209 :

```rs
            <div>
                <div
                    class="foo"
                    class="foo"
                    class="foo"
                    class="foo"
                    class="foo"
                    class="foo"
                    class="foo"
                >
                    <i class="bi-google"></i>
                    "Sign in with google"
                </div>
            </div>
```

formats to

```diff
            <div>
                <div
                    class="foo"
                    class="foo"
                    class="foo"
                    class="foo"
                    class="foo"
                    class="foo"
                    class="foo"
                >
+                                                                                                                                                                                                                                   
                    <i class="bi-google"></i>
                    "Sign in with google"
                </div>
            </div>
```

I am trying to look into this as well, but can't figure out how to fix the issue yet

**Comment by bram209** [comment]
ah check, I think I know the issue, sorry for the inconvenience

**Comment by seblj** [comment]
No problem at all! Thanks for looking into it :)

**Comment by bram209** [comment]
Should be fixed now @seblj

**Comment by seblj** [comment]
Works perfectly! Thank you!

**Pull request merged**
